### ISSUE TITLE
Latest stable release bundle unavailable

### ISSUE THREAD

**Issue by andreyev** [saleemshafi/nexus-artifact-usage-plugin#11]
The latest stable release bundle (https://github.com/downloads/saleemshafi/nexus-artifact-usage-plugin/artifact-usage-plugin-0.8-bundle.zip) is unavailable (error 403). Should I build it from source? How?

TIA!

**Comment by saleemshafi** [comment]
I've deleted and re-uploaded the artifact and it seems to be working now.

Thanks for letting me know about the problem.

**Comment by andreyev** [comment]
On Thu, Nov 10, 2011 at 12:41 PM, Saleem Shafi
reply@reply.github.com
wrote:

> I've deleted and re-uploaded the artifact and it seems to be working now.
> 
> Thanks for letting me know about the problem.

## Thank you so much to fix this issue and develop this plugin!!!

Andreyev
