### ISSUE TITLE
Update dependencies / fix build

### ISSUE THREAD

**Issue by myron0815** [saleemshafi/nexus-artifact-usage-plugin#13]
Currently, it's not possible to checkout and build the thing.
I was missing com.google.atinject (which i downloaded and installed locally)
But now i'm still missing all the -SONATYPE patched JARs.

Reading there, this issue has been resolved
https://issues.sonatype.org/browse/NEXUS-4912

So, a "simple" update of some dependencies should fix this?!

(a binary download of the latest snapshot would solve this as well ;o)

**Comment by saleemshafi** [comment]
my apologies, i've let this project get a bit stale and it might take me a little while to get back into it..  can you give me a few days and i'll try all this with the latest version of Nexus and update as necessary?  hopefully i can get it fixed for you this weekend..  of course, if you wanted to send me a pull request, i'd be happy with that, as well :)

which version of Nexus are you working with, btw?

**Comment by myron0815** [comment]
Hi,
thanks for your fast response!
I discovered this plugin months ago - but never had the time to test it. 
Today i rediscovered it, and saw some recent commits for nexus 2.x, so i wanted to give it a try :)

currently using 2.0.2, but the latest 2.0.5 will be fine (planning upgrande anyway)
Don't feel stressed; if it does what it suggests, i'll call this really a must-have-plugin :)

**Comment by saleemshafi** [comment]
hello..  i managed to get my environment back up and running again and i updated the code to support Nexus 2.0.5..  i also added the appropriate repositories to the pom file, so you should be able to build it yourself now, but i've also updated a new binary..

bonus: it still seems to work!  let me know if what you think.

**Comment by myron0815** [comment]
Thanks :)
builds now....

Now for the testing.....
