### ISSUE TITLE
Compatibility with Nexus 3.8 ?

### ISSUE THREAD

**Issue by cmarchand** [saleemshafi/nexus-artifact-usage-plugin#22]
Hello !
does someone have tested this plugin with a Nexus 3.8 ?

Best,
Christophe

**Comment by bguerin** [comment]
Will not work with Nexus 3.x

Nexus 3 has been completly rewritten comparing to Nexus 2. Plugins working on Nexus 2 have to be rewritten too to work with Nexus 3

**Comment by cmarchand** [comment]
Ok, thanks a lot.
